ShoeShop/ShoeShop.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ShoeShop.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

ShoeShop/ShoeShop.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShoeShop.Library.Contexts;
using ShoeShop.Library.Models;
using ShoeShop.Library.Services;

namespace ShoeShop.Web.Pages.Products
{
    public class IndexModel(ShoeDbContext context, OrderService service) : PageModel
    {
        public IList<Product> Product { get;set; } = default!;
        
        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string? MaxPrice { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? Manufacturer { get; set; } = "0";
        
        [BindProperty(SupportsGet = true)]
        public string? SortColumn { get; set; }

        [BindProperty(SupportsGet = true)] 
        public bool IsHasDiscountFlag { get; set; } = false;
        
        [BindProperty(SupportsGet = true)]
        public bool IsHasFlag { get; set; } = false;

        public async Task OnGetAsync()
        {
            var manufacturers = await context.Manufacturers.ToListAsync();
            manufacturers.Add(new Manufacturer{Title = "Все"});
            ViewData["Manufacturer"] = new SelectList(manufacturers, "ManufacturerId", "Title");
            
            var products = context.Products
                .Include(p => p.Category)
                .Include(p => p.Image)
                .Include(p => p.Manufacturer)
                .Include(p => p.Supplier).AsQueryable();
            
            products = IsHasFlag ? products.Where(p => p.Quantity > 0) : products;
            products = IsHasDiscountFlag ? products.Where(p => p.Discount > 0) : products;
            
            products = SortColumn switch
            {
                "price" => products.OrderBy(p => p.Price * (1 - (decimal)p.Discount / 100)),
                "price_desc" => products.OrderByDescending(p => p.Price * (1 - (decimal)p.Discount / 100)),
                "title" => products.OrderBy(p => p.Title),
                "supplier" => products.OrderBy(p => p.Supplier.Title),
                _ => products
            };
            
            if (!string.IsNullOrEmpty(SearchString))
                products = products.Where(p => p.Description.Contains(SearchString, StringComparison.OrdinalIgnoreCase));
            
            if (!string.IsNullOrEmpty(MaxPrice) && decimal.TryParse(MaxPrice, out decimal maxPrice))
                products = products.Where(p => p.Price <= maxPrice);

            if (!string.IsNullOrWhiteSpace(Manufacturer) && int.TryParse(Manufacturer, out int manufacturerId) && manufacturerId != 0)
                products = products.Where(p => p.ManufacturerId == manufacturerId);
            
            Product = await products.ToListAsync();
        }

        public async Task<IActionResult> OnPostAsync(string article)
        {
            var role = HttpContext.Session.GetString("Role");
            if (role == "Гость" || role is null)
                return RedirectToPage("/Login");

            var order = await service.CreateAsync(new()
            {
                UserId = int.Parse(HttpContext.Session.GetString("UserId")),
                Articles = [article]
            });

            return RedirectToPage("/Index");
        }
    }
}

ShoeShop/ShoeShop.Web/Pages/Login.cshtml.cs
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShoeShop.Library.Contexts;
using ShoeShop.Library.Dtos.Users;
using ShoeShop.Library.Services;

namespace ShoeShop.Web.Pages;

public class Login(ShoeDbContext context) : PageModel
{
    public IActionResult OnGet()
    {
        ViewData["RoleId"] = new SelectList(context.Roles, "RoleId", "RoleId");
        return Page();
    }

    [BindProperty]
    public UserAuthDto User { get; set; } = default!;

    // For more information, see https://aka.ms/RazorPagesCRUD.
    public IActionResult OnGetLogout()
    {
        HttpContext.Session.Clear();
        return RedirectToPage("/Index");
    }

    public async Task<IActionResult> OnPostLoginAsync()
    {
        var user = await context.Users
            .Include(u => u.Role)
            .FirstOrDefaultAsync(u => u.Email == User.Email);

        if (user is null || !PasswordService.VerificationPassword(User.Password, user.Passwordhash))
            return Page();

        HttpContext.Session.SetString("Fullname", $"{user.Surname} {user.Name} {user.Patronymic ?? string.Empty}".Trim());
        HttpContext.Session.SetString("Role", user.Role.Title);
        HttpContext.Session.SetString("UserId", user.UserId.ToString());
        return RedirectToPage("/Index");
    }

    public async Task<IActionResult> OnPostGuestAsync()
    {
        HttpContext.Session.Clear();
        HttpContext.Session.SetString("Role", "Гость");
        return RedirectToPage("/Index");
    }
}

ShoeShop/ShoeShop.Web/Pages/Orders/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ShoeShop.Library.Contexts;
using ShoeShop.Library.Models;
using ShoeShop.Web.Dtos.Orders;

namespace ShoeShop.Web.Pages.Orders
{
    public class IndexModel(ShoeDbContext context) : PageModel
    {
        public IList<OrderShortDto> Order { get;set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            var role = HttpContext.Session.GetString("Role");
            if (role == "Гость" || role is null)
                return RedirectToPage("~/Login");


            var orders = context.Orders
                .Include(o => o.User)
                .Include(o => o.OrderProducts)
                .ThenInclude(o => o.ArticleNavigation)
                .AsQueryable();

            orders = role switch
            {
                "Клиент" => orders.Where(o => o.UserId == int.Parse(HttpContext.Session.GetString("UserId"))),
                _ => orders
            };
            
            Order = await orders.Select(o => new OrderShortDto()
            {
                Code = o.Code,
                Date = o.OrderDate,
                Articles = string.Join('\n', o.OrderProducts.Select(op => op.Article).ToList()),
                Total = o.OrderProducts.Sum(op => op.ArticleNavigation.Price * (1 - (decimal)op.ArticleNavigation.Discount / 100) * op.Quantity),
            }).ToListAsync();
            
            return Page();
        }
    }
}

ShoeShop/ShoeShop.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ShoeShop.Web.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

ShoeShop/ShoeShop.Web/Pages/Index.cshtml
@page
@model ShoeShop.Web.Pages.Products.IndexModel

@{
    ViewData["Title"] = "Товары";
}

<h1>Товары</h1>

<form method="get">
    <input type="text"
           name="filmTitle"
           value="@Model.SearchString"
           placeholder="Поиск..."
           onchange="this.form.submit()"
           class="form-control" />
    
    <input type="text"
           name="maxPrice"
           value="@Model.MaxPrice"
           placeholder="Максимальная стоимость товара"
           onchange="this.form.submit()"
           class="form-control" />

    <select class="form-control"
            name="sortColumn"
            onchange="this.form.submit()">
        <option value="price" selected="@(Model.SortColumn == "price")">
            По цене (дешевые)
        </option>
        <option value="price_desc" selected="@(Model.SortColumn == "price_desc")">
            По цене (дорогие)
        </option>
        <option value="title" selected="@(Model.SortColumn == "title")">
            По названию
        </option>
        <option value="supplier" selected="@(Model.SortColumn == "supplier")">
            По поставщику
        </option>
    </select>

    <select class="form-control" asp-items="ViewBag.Manufacturer"
            asp-for="Manufacturer"
            name="manufacturer"
            onchange="this.form.submit()">
    </select>

    <div class="form-check">
        <input asp-for="IsHasFlag" class="form-check-input" onchange="this.form.submit()"/>
        <label asp-for="IsHasFlag" class="form-check-label">
            Есть на складе
        </label>
    </div>
    <div class="form-check">
        <input asp-for="IsHasDiscountFlag" class="form-check-input" onchange="this.form.submit()"/>
        <label asp-for="IsHasDiscountFlag" class="form-check-label">
            Есть скидка
        </label>
    </div>
</form>

@foreach (var product in Model.Product)
{
    <div class="product-container">
        <img class="image-container"
             src="@(product.Image is null ? "images/picture.png" : $"data:image/jpeg;base64,{Convert.ToBase64String(product.Image.Bytes)}")"
             alt="Пусто"/>
        <div class="info-block">
            <p>
                @product.Category.Title | @product.Title <br/>
                Описание товара: @product.Description <br/>
                Производитель: @product.Manufacturer.Title <br/>
                Поставщик: @product.Supplier.Title <br/>
                Цена: @if (product.Discount > 0)
                      {
                          <s>@product.Price</s> @(product.Price * (1 - (decimal)product.Discount / 100)) 
                      }
                      else
                      {
                          @product.Price
                      }
                рублей<br/>
                Единица измерения: @product.MeasurementUnit <br/>
                Количество на складе: @product.Quantity
            </p>
        </div>
        <div>
            <div class="@(product.Discount > 15 ? "special-discount-info" : "discount-info")">
                @product.Discount %
            </div>
            <form method="post">
                <div class="form-group">
                    <input type="submit" value="Заказать"
                           asp-route-article="@product.Article"
                           class="btn btn-primary"/>
                </div>
            </form>
        </div>
        
    </div>
}

ShoeShop/ShoeShop.Web/Pages/Login.cshtml
@page
@model ShoeShop.Web.Pages.Login

@{
    ViewData["Title"] = "Авторизация";
}

<h1>Авторизация</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="User.Email" class="control-label">Логин</label>
                <input asp-for="User.Email" class="form-control" />
                <span asp-validation-for="User.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User.Password" class="control-label">Пароль</label>
                <input asp-for="User.Password" class="form-control" type="password"/>
                <span asp-validation-for="User.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Войти" class="btn btn-primary" />
            </div>
        </form>

        <form method="post" asp-page-handler="Guest">
            <div class="form-group">
                <input type="submit" value="Гость" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Вернуться обратно на страницу</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShoeShop/ShoeShop.Web/Pages/Orders/Index.cshtml
@page
@using System.Text
@model ShoeShop.Web.Pages.Orders.IndexModel

@{
    ViewData["Title"] = "Заказы";
}

<h1>Заказы</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Код
            </th>
            <th>
                Состав
            </th>
            <th>
                Дата заказа
            </th>
            <th>
                Итоговая стоимость
            </th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Order)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                <p>
                    @Html.DisplayFor(modelItem => item.Articles)
                </p>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total) рублей
            </td>
        </tr>
    }
    </tbody>
</table>

ShoeShop/ShoeShop.Web/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor Accessor;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ShoeShop.Web.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">Магазин обуви</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>
                        @if (Accessor.HttpContext.Session.GetString("Role") is not null)
                        {
                            <a class="nav-link text-dark" asp-area="" asp-page="/Orders/Index">Заказы</a>
                        }
                    </li>
                </ul>
            </div>
            @if (Accessor.HttpContext.Session.GetString("Role") is null)
            {
                <a asp-page="/Login" asp-page-handler="Login" class="btn btn-primary">Войти</a>
            }
            else
            {
                @Accessor.HttpContext.Session.GetString("Fullname");
                <a asp-page="/Login" asp-page-handler="Logout" class="btn btn-primary">Выйти</a>
            }
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - ShoeShop.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>